#!/usr/bin/env node
/*
 * Writes src/config/env.generated.ts (git-ignored) from the environment:
 *   XTREAM_DNS1, XTREAM_USERNAME, XTREAM_PASSWORD, M3U (and optional XTREAM_LABEL).
 * - Unset variables become empty strings.
 * - If the file already exists and none of the variables are set, it is left untouched.
 * - Never prints secret values.
 */
'use strict';

const fs = require('fs');
const path = require('path');

const OUT = path.join(__dirname, '..', 'src', 'config', 'env.generated.ts');
const REL = path.relative(process.cwd(), OUT) || OUT;

const vars = {
  baseUrl: process.env.XTREAM_DNS1,
  username: process.env.XTREAM_USERNAME,
  password: process.env.XTREAM_PASSWORD,
  m3u: process.env.M3U,
};
const label = process.env.XTREAM_LABEL || 'My line';

const anySet = Object.values(vars).some(v => typeof v === 'string' && v.length > 0);

if (fs.existsSync(OUT) && !anySet) {
  console.log(`gen-env: ${REL} already exists and no XTREAM_*/M3U variables are set — left untouched.`);
  process.exit(0);
}

const values = {
  baseUrl: vars.baseUrl || '',
  username: vars.username || '',
  password: vars.password || '',
  m3u: vars.m3u || '',
  label,
};

const content =
  '// GENERATED by scripts/gen-env.js — do not edit, do not commit (git-ignored).\n' +
  'export const ENV = {\n' +
  `  baseUrl: ${JSON.stringify(values.baseUrl)},\n` +
  `  username: ${JSON.stringify(values.username)},\n` +
  `  password: ${JSON.stringify(values.password)},\n` +
  `  m3u: ${JSON.stringify(values.m3u)},\n` +
  `  label: ${JSON.stringify(values.label)},\n` +
  '};\n';

fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(OUT, content, 'utf8');

const status = k => (values[k] ? 'set' : 'empty');
console.log(
  `gen-env: wrote ${REL} (baseUrl: ${status('baseUrl')}, username: ${status('username')}, ` +
    `password: ${status('password')}, m3u: ${status('m3u')}, label: ${JSON.stringify(label)})`,
);
