#!/usr/bin/env node
/*
 * Writes src/config/env.generated.ts (git-ignored) from the environment:
 *   XTREAM_DNS1, XTREAM_USERNAME, XTREAM_PASSWORD, M3U (and optional XTREAM_LABEL).
 * - Unset variables become empty strings.
 * - If the file already exists and none of the variables are set, it is left untouched.
 * - Never prints secret values.
 */
'use strict';

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const OUT = path.join(ROOT, 'src', 'config', 'env.generated.ts');
const REL = path.relative(process.cwd(), OUT) || OUT;

// Minimal .env loader (Node does not read .env on its own, and we avoid adding a dependency).
function loadDotEnv(file) {
  const out = {};
  if (!fs.existsSync(file)) {
    return out;
  }
  for (const raw of fs.readFileSync(file, 'utf8').split(/\r?\n/)) {
    const line = raw.trim();
    if (!line || line.startsWith('#')) {
      continue;
    }
    const eq = line.indexOf('=');
    if (eq === -1) {
      continue;
    }
    let key = line.slice(0, eq).trim();
    if (key.startsWith('export ')) {
      key = key.slice('export '.length).trim();
    }
    let value = line.slice(eq + 1).trim();
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    out[key] = value;
  }
  return out;
}

// Real environment variables win; .env / .env.local fill in the rest.
const dotenv = {
  ...loadDotEnv(path.join(ROOT, '.env')),
  ...loadDotEnv(path.join(ROOT, '.env.local')),
};
const pick = k => (process.env[k] != null && process.env[k] !== '' ? process.env[k] : dotenv[k]);

const vars = {
  baseUrl: pick('XTREAM_DNS1'),
  username: pick('XTREAM_USERNAME'),
  password: pick('XTREAM_PASSWORD'),
  m3u: pick('M3U'),
};
const label = pick('XTREAM_LABEL') || 'My line';
// Player mode: auto (AVPlayer, VLC only for HEVC-in-TS on Apple) | vlc (VLC for everything) | avplayer
const player = pick('PITWALL_PLAYER') || 'auto';

const anySet = Object.values(vars).some(v => typeof v === 'string' && v.length > 0);

if (fs.existsSync(OUT) && !anySet) {
  console.log(`gen-env: ${REL} already exists and no XTREAM_*/M3U variables are set — left untouched.`);
  process.exit(0);
}

const values = {
  baseUrl: vars.baseUrl || '',
  username: vars.username || '',
  password: vars.password || '',
  m3u: vars.m3u || '',
  label,
  player,
};

const content =
  '// GENERATED by scripts/gen-env.js — do not edit, do not commit (git-ignored).\n' +
  'export const ENV = {\n' +
  `  baseUrl: ${JSON.stringify(values.baseUrl)},\n` +
  `  username: ${JSON.stringify(values.username)},\n` +
  `  password: ${JSON.stringify(values.password)},\n` +
  `  m3u: ${JSON.stringify(values.m3u)},\n` +
  `  label: ${JSON.stringify(values.label)},\n` +
  `  player: ${JSON.stringify(values.player)},\n` +
  '};\n';

fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(OUT, content, 'utf8');

const status = k => (values[k] ? 'set' : 'empty');
console.log(
  `gen-env: wrote ${REL} (baseUrl: ${status('baseUrl')}, username: ${status('username')}, ` +
    `password: ${status('password')}, m3u: ${status('m3u')}, label: ${JSON.stringify(label)}, player: ${JSON.stringify(player)})`,
);
